// <auto-generated />
using System;
using AtendimentoDeCampo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtendimentoDeCampo.Infrastructure.Migrations
{
    [DbContext(typeof(AtendimentoDbContext))]
    [Migration("20260726163422_CodigoDoPaciente")]
    partial class CodigoDoPaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ClassificacaoRisco")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FinalizadoPorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PrecisaoMetros")
                        .HasColumnType("double precision");

                    b.Property<string>("QueixaPrincipal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassificacaoRisco");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("FinalizadoPorId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("BaseId", "CriadoEm");

                    b.HasIndex("BaseId", "Status");

                    b.ToTable("atendimentos", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Campo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Especialidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("AtendimentoId", "CriadaEm");

                    b.ToTable("auditorias", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Base", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PrefixoCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("PrefixoCodigo")
                        .IsUnique();

                    b.ToTable("bases", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Cid10", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Capitulo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DescricaoEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DescricaoEs")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DescricaoPt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Codigo");

                    b.HasIndex("DescricaoPt");

                    b.ToTable("cid10", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cid10Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Conduta")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Desfecho")
                        .HasColumnType("integer");

                    b.Property<string>("DiagnosticoObservacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EncaminhadoPara")
                        .HasColumnType("integer");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("PerdasVivenciadas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("SintomasDescricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int[]>("SintomasSaudeMental")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("Cid10Codigo");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.ConsultaOrtopedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Imobilizacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MecanismoTrauma")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("NecessitaRaioX")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("consultas_ortopedia", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Dispensacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoLivre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("JustificativaItemLivre")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Posologia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Unidade")
                        .HasColumnType("integer");

                    b.Property<int?>("Via")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ItemId");

                    b.ToTable("dispensacoes", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Enfermagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Desfecho")
                        .HasColumnType("integer");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OutroProcedimento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int[]>("Procedimentos")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("enfermagem", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.EstoqueBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("BaseId", "ItemId")
                        .IsUnique();

                    b.ToTable("estoque_base", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Especialidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Status");

                    b.HasIndex("AtendimentoId", "Especialidade")
                        .IsUnique();

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.ItemCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Concentracao")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Forma")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrincipioAtivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Unidade")
                        .HasColumnType("integer");

                    b.Property<int[]>("ViasPermitidas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Nome", "Concentracao", "Forma")
                        .IsUnique();

                    b.ToTable("itens_catalogo", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.MarcacaoDente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Dente")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int[]>("Faces")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("OdontologiaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Dente");

                    b.HasIndex("OdontologiaId", "Dente", "Estado")
                        .IsUnique();

                    b.ToTable("marcacoes_dente", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Odontologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cid10Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("Desfecho")
                        .HasColumnType("integer");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutroProcedimento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int[]>("Procedimentos")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Queixa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Cid10Codigo");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("odontologia", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int[]>("CondicoesCronicas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("ConsentimentoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentimentoRegistro")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int?>("IdadeAproximada")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("OutraCondicaoCronica")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<int>("StatusAlergia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<int[]>("Vulnerabilidades")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique()
                        .HasFilter("\"NumeroDocumento\" IS NOT NULL");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.PassagemFila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EntrouEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Especialidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SaiuEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("Especialidade", "EntrouEm");

                    b.ToTable("passagens_fila", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConselhoTipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhAdministrador")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Funcao")
                        .HasColumnType("integer");

                    b.Property<int>("Idioma")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Registro")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevisadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("RevisadoPorId");

                    b.HasIndex("Status");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Triagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ClassificacaoRisco")
                        .HasColumnType("integer");

                    b.Property<int?>("Encaminhamento")
                        .HasColumnType("integer");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("integer");

                    b.Property<int?>("GlicemiaCapilar")
                        .HasColumnType("integer");

                    b.Property<string>("MedicamentosEmUso")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OutroSintoma")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("PressaoDiastolica")
                        .HasColumnType("integer");

                    b.Property<int?>("PressaoSistolica")
                        .HasColumnType("integer");

                    b.Property<int?>("SaturacaoO2")
                        .HasColumnType("integer");

                    b.Property<int[]>("Sintomas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("StatusAlergia")
                        .HasColumnType("integer");

                    b.Property<double?>("TemperaturaCelsius")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId")
                        .IsUnique();

                    b.ToTable("triagens", (string)null);
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Atendimento", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Base", "Base")
                        .WithMany("Atendimentos")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.Profissional", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.Profissional", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtendimentoDeCampo.Domain.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("CriadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Auditoria", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Atendimento", "Atendimento")
                        .WithMany("Auditorias")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Consulta", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Cid10", "Cid10")
                        .WithMany()
                        .HasForeignKey("Cid10Codigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtendimentoDeCampo.Domain.Etapa", "Etapa")
                        .WithOne("Consulta")
                        .HasForeignKey("AtendimentoDeCampo.Domain.Consulta", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cid10");

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.ConsultaOrtopedia", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Consulta", "Consulta")
                        .WithOne("Ortopedia")
                        .HasForeignKey("AtendimentoDeCampo.Domain.ConsultaOrtopedia", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Dispensacao", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Etapa", "Etapa")
                        .WithMany("Dispensacoes")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.ItemCatalogo", "Item")
                        .WithMany("Dispensacoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Etapa");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Enfermagem", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Etapa", "Etapa")
                        .WithOne("Enfermagem")
                        .HasForeignKey("AtendimentoDeCampo.Domain.Enfermagem", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.EstoqueBase", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Base", "Base")
                        .WithMany("Estoque")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.ItemCatalogo", "Item")
                        .WithMany("Estoques")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Etapa", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Atendimento", "Atendimento")
                        .WithMany("Etapas")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtendimentoDeCampo.Domain.Profissional", "Profissional")
                        .WithMany("Etapas")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atendimento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.MarcacaoDente", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Odontologia", "Odontologia")
                        .WithMany("Marcacoes")
                        .HasForeignKey("OdontologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odontologia");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Odontologia", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Cid10", "Cid10")
                        .WithMany()
                        .HasForeignKey("Cid10Codigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AtendimentoDeCampo.Domain.Etapa", "Etapa")
                        .WithOne("Odontologia")
                        .HasForeignKey("AtendimentoDeCampo.Domain.Odontologia", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cid10");

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.PassagemFila", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Atendimento", "Atendimento")
                        .WithMany("PassagensFila")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Profissional", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Profissional", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RevisadoPor");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Triagem", b =>
                {
                    b.HasOne("AtendimentoDeCampo.Domain.Etapa", "Etapa")
                        .WithOne("Triagem")
                        .HasForeignKey("AtendimentoDeCampo.Domain.Triagem", "EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Atendimento", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Etapas");

                    b.Navigation("PassagensFila");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Base", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Consulta", b =>
                {
                    b.Navigation("Ortopedia");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Etapa", b =>
                {
                    b.Navigation("Consulta");

                    b.Navigation("Dispensacoes");

                    b.Navigation("Enfermagem");

                    b.Navigation("Odontologia");

                    b.Navigation("Triagem");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.ItemCatalogo", b =>
                {
                    b.Navigation("Dispensacoes");

                    b.Navigation("Estoques");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Odontologia", b =>
                {
                    b.Navigation("Marcacoes");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Paciente", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("AtendimentoDeCampo.Domain.Profissional", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
